### ISSUE TITLE
add missing dependency in make example

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/reproducible-research#21]
https://github.com/aaronpeikert/reproducible-research/blob/9107c1490c03e7d080fe68b8b3dd55213450cdc9/manuscript.Rmd#L160
analysis.Rmd is missing.

**Comment by brandmaier** [comment]
I added this. I also took the liberty of revising the example and surrounding text to increase clarity. Please check whether I introduced errors when renaming the files in the example, @aaronpeikert. Thanks!

**Comment by aaronpeikert** [comment]
97d6c1a

**Comment by aaronpeikert** [comment]
Two things:
1. should we include an all target in the example?
2. Is the naming of files (namely report and preprocessed) consistent:
    * within the paper
    * in the [example](https://github.com/aaronpeikert/workflow-showcase)
    * with [WORCS](https://github.com/cjvanlissa/worcs)

I will check that later...

**Comment by brandmaier** [comment]
Very good point! Let's make it WORCS-compatible and rename (again) to manuscript.Rmd.
I haven't touched the example, yet.

**Comment by brandmaier** [comment]
all target is added now
any other compatibility issues reamining, @aaronpeikert ?

**Comment by aaronpeikert** [comment]
I think we can close this. Feel free to reopen when you detect other issues.
