### ISSUE TITLE
Conditional formatting of code chunks

### ISSUE THREAD

**Issue by brandmaier** [aaronpeikert/reproducible-research#22]
Is it possible to format code chunks differently depending on whether they contain bash or R code?

Say, they should have frames in different colors, strokes or line width, and/or a little label that tells the type of code.

**Comment by brandmaier** [comment]
I was playing around with knit hooks but I am not really sure how to create something nice with it.

**Comment by aaronpeikert** [comment]
Nice idea, couldn’t we define special environments in latex and then use a knitr posthooks?

A low tech alternative I was thinking about is to include a shebang (#! Rscript) in each chunk, but that is probably to techy.

**Comment by brandmaier** [comment]
but how do you redefine the chunk environment in a posthook at all?

**Comment by brandmaier** [comment]
Let's close this because it's not relevant for the resubmission.
