### ISSUE TITLE
CC0 License

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/reproducible-research#24]
@brandmaier we should make the paper CC0 license (if we haven't already)
This issue is just a reminder for myself.

**Comment by brandmaier** [comment]
QCMB publishes under CC-BY 4.0. Wouldn't this license be more appropriate then?

**Comment by aaronpeikert** [comment]
While I would prefer CC0, CC-BY is perfectly fine (and I am grateful that they allow that)
I would oppose CC-SA though.

**Comment by aaronpeikert** [comment]
Why have I brought that up we have added the licence months ago...
b89317b062d148e76e3d4ac3f8ebcef9af9064a5

**Comment by brandmaier** [comment]
Isn't git great?!?!
