### ISSUE TITLE
Two typos in Rmd

### ISSUE THREAD

**Issue by gabrielesh** [aaronpeikert/reproducible-research#3]
Hi Aaron,
I'll say again how much I enjoyed your paper. I thought I'd mention two small typos in Manuscript.Rmd that I noticed while reading your manuscript. Wasn't sure if you prefer issues or pull requests, so I thought I'd make this an issue to start. 

1. The first is that at line 245 you write "There are two principled ways to share a Docker image"; I think you meant "There are two principal ways to share a Docker image." Principled would mean "having principles," where as you seem to mean "primary ways." See https://www.merriam-webster.com/dictionary/principal?utm_campaign=sd&utm_medium=serp&utm_source=jsonld 

2. The second is at line 349, where your code to reproduce the reproducible analysis working example has the user clone workflow-showcase, but then `cd reproducible-research`. 

Thanks,
Gabriele

**Comment by aaronpeikert** [comment]
Thank you so much I will correct them asap.

**Comment by aaronpeikert** [comment]
Hey Gabriel,
I am delighted to take a pull request anytime. It is wonderful that you have put in so much effort into these issues. If you have any other suggestions on how to improve this (e.g. make it easier; things we forgot) go ahead.
