### ISSUE TITLE
Rendering with floatsintext

### ISSUE THREAD

**Issue by brandmaier** [aaronpeikert/reproducible-research#38]
When calling `make DOCKER=TRUE`, the document is rendered with all images at the end of the document even though the YAML header specifies "floatsintext      : yes".

**Comment by aaronpeikert** [comment]
I get this 
[manuscript.pdf](https://github.com/aaronpeikert/reproducible-research/files/4649412/manuscript.pdf) version with images in text and **not** at the end.

**Comment by aaronpeikert** [comment]
I have added a `make rebuild` target which build the docker image without cache (reinstalling all packages), could you try that?

**Comment by brandmaier** [comment]
This did the job!
