### ISSUE TITLE
Mismatch between Figure 2 and Figure 3

### ISSUE THREAD

**Issue by brandmaier** [aaronpeikert/reproducible-research#39]
There is quite some mismatch between Figure 2 and Figure 3. The rendered document shows more (title and authors) but also less (final line) then the source figure.

**Comment by aaronpeikert** [comment]
Oh that is indeed extreme. Thanks for spotting.

**Comment by brandmaier** [comment]
With this commit, https://github.com/aaronpeikert/reproducible-research/commit/2996207f04d757e8c21792e0e807c4007d79e458, I suggest some changes to the example to make it more concise. Also note that this is not "students'" but "Student's" as in William Gosset. Also, changed p value to conventional <.05. Last, added `paired = TRUE` as in the official `t.test` man page.

I think I have broken the croping. Please check and fix, @aaronpeikert. Thanks!

**Comment by brandmaier** [comment]
Crop of Figure 3 is too tight ( `paired = TRUE` is cut off).
<img width="358" alt="Screenshot 2020-05-19 at 21 55 21" src="https://user-images.githubusercontent.com/116031/82372030-81298d80-9a1b-11ea-9063-fd014454897e.png">
