### ISSUE TITLE
RStudio webserver security issue

### ISSUE THREAD

**Issue by brandmaier** [aaronpeikert/reproducible-research#41]
Is it a potential security issue to run RStudio on a local port (which accidentally could be open in a LAN/WAN? Mention this issue? Or tell people not to use 8787 but a number they come up with?

**Comment by aaronpeikert** [comment]
That is indeed a critical security issue:
https://www.tripwire.com/state-of-security/devops/psa-beware-exposing-ports-docker/
So you are correct in your guess that this port is opened to the network of the user.
I think we can mitigate the issue with this answer:
https://superuser.com/questions/1171108/expose-docker-port-internally

**Comment by aaronpeikert** [comment]
@brandmaier do you think this is enough?

**Comment by aaronpeikert** [comment]
Could @brandmaier  you check that you can run
`docker run -e PASSWORD=test -p 127.0.0.1:8787:8787 reproducible-research`
and then connect via web-browser?

**Comment by brandmaier** [comment]
Confirm that this works on macOS.
