### ISSUE TITLE
Broken shorttitle

### ISSUE THREAD

**Issue by brandmaier** [aaronpeikert/reproducible-research#48]
Shorttitle is broken. 

<img width="559" alt="Screenshot 2020-05-19 at 21 40 04" src="https://user-images.githubusercontent.com/116031/82370788-60f8cf00-9a19-11ea-8008-a899b86a2a33.png">

**Comment by brandmaier** [comment]
PS: Our affiliations are also gone.

**Comment by brandmaier** [comment]
It works if I run `make` locally but not if I run `make DOCKER=TRUE`.

This is the docker output:

<img width="587" alt="Screenshot 2020-05-20 at 09 51 31" src="https://user-images.githubusercontent.com/116031/82420056-828ca180-9a7f-11ea-9327-c78ad4630af8.png">

**Comment by aaronpeikert** [comment]
That is a funny issue. It is one of the dependencies of papaja that seems to introduce the issue, but only with the cran versions of around the date 2019-12-12 (which is the last day when 3.6.1 the most recent R version). It works on 4.0.0, 3.5.0, 3.6.0.

This brought to light that ARG BUILD_DATE=2019-11-11 doesn't help. #49

**Comment by brandmaier** [comment]
great example of non-reproducibility because dependencies further down the hierarchy have changed.

**Comment by aaronpeikert** [comment]
Now I don't know if I should fix the date of the build or if I should lower the R version to 3.6.0?

**Comment by brandmaier** [comment]
I am OK with either lowering R version to 3.6.0 or updating to 4.0.0.

**Comment by aaronpeikert** [comment]
The upside of downgrading to 3.6.0 is that we could fully swap 3.6.1 then users only need two R containers (3.5.0 and 3.6.0 instead of 3.5.0, 3.6.1 and 4.0.0.

We could also merge #52
But this dockerfile now really looks complicated.
