### ISSUE TITLE
Link to release v0.2.1 appears to be broken

### ISSUE THREAD

**Issue by jake-wittman** [aaronpeikert/reproducible-research#56]
The link in footnote 2 on page 11 of the preprint to release version 0.2.1 is broken. Looking at your repository, it looks like v0.2.1 does not exist as a release - I could only find v0.2.0. 

Thanks for the paper! I've been looking for something like this.

**Comment by aaronpeikert** [comment]
Oh thanks for spotting and thanks for notifying me! Forgot to click on release... Now it should be working!
