### ISSUE TITLE
explicitly endorse CC-BY

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/reproducible-research#61]
I know Andreas that you like CC-BY best, however, I think we should endorse CC0 instead because I think good academic practice should warrants a citation/mention of the authors and not licence law.
I'll rewrite it for CC-BY away, but if you are persuaded let me know.

**Comment by brandmaier** [comment]
Good point. I agree that for academic purposes, the rules of good scientific practice to which scientists are committed, should guarantee proper citation. However, open materials/manuscripts/etc are released to the entire world including the corporate world, which need to be reminded (if necessary by a legal disclaimer) that they need to acknowledge the source they draw materials from.

**Comment by aaronpeikert** [comment]
OK, you have convinced me that such a recommendation would do more good than harm.
