### ISSUE TITLE
make more explicit that redoc is reversable / allows for a round trip .Rmd -> .docx -> .Rmd

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/reproducible-research#67]

**Comment by brandmaier** [comment]
This sounds to good to be true. When does it break?

**Comment by aaronpeikert** [comment]
Unfortunately, the development is suspended. Of course, you can not edit the results of R code chunks, and expect this to work. I also don't know how well formatting changes (beyond markdown possible stuff) is handled. Most likely changing references won't work and Open Office is not supported. But beyond these limitations it works pretty well.
