### ISSUE TITLE
Link to most recent release

### ISSUE THREAD

**Issue by brandmaier** [aaronpeikert/reproducible-research#73]
In the manuscript, we link to the most recent release:
```
[^sub]: We created an release for the submission: [https://github.com/aaronpeikert/reproducible-research/releases/tag/v0.2.1-submission](https://github.com/aaronpeikert/reproducible-research/releases/tag/v0.2.1-submission)
```

Does this need an update?

**Comment by aaronpeikert** [comment]
I would add a link to the initial submission there and a link that points always to the most recent release as a footnote behind publication?
